from pathlib import Path

GLOBAL_MAX_SPEED = 45.0
GLOBAL_MAX_LANE_LENGTH = 30000

SPEED_NORMALIZATION = 15
LANE_LENGTH_NORMALIZATION = 250

TL_CYCLE_NORMALIZATION = 100
MAX_TL_CYCLE = 600

GUI_SETTINGS_FILE = Path('resources/sumo_static/gui.xml')